export const AUTH = {
  LOGIN_REQUEST: '[AUTH] LOGIN_REQUEST',
  LOGIN_SUCCESS: '[AUTH] LOGIN_SUCCESS',
  LOGIN_FAILURE: '[AUTH] LOGIN_FAILURE',
  SIGNUP_REQUEST: '[AUTH] SIGNUP_REQUEST',
  SIGNUP_SUCCESS: '[AUTH] SIGNUP_SUCCESS',
  SIGNUP_FAILURE: '[AUTH] SIGNUP_FAILURE',
  REQUEST_LOGOUT: '[AUTH] REQUEST_LOGOUT',
  LOGOUT: '[AUTH] LOGOUT',
};

export const GAME = {
  CREATE_GAME_REQUEST: '[GAME] CREATE_GAME_REQUEST',
  CREATE_GAME_SUCCESS: '[GAME] CREATE_GAME_SUCCESS',
  CREATE_GAME_FAILURE: '[GAME] CREATE_GAME_FAILURE',
  GET_GAME_REQUEST: '[GAME] GET_GAME_REQUEST',
  GET_GAME_SUCCESS: '[GAME] GET_GAME_SUCCESS',
  GET_GAME_FAILURE: '[GAME] GET_GAME_FAILURE',
}