export const AUTH = {
  LOGIN_REQUEST: '[AUTH] LOGIN REQUEST',
  LOGIN_SUCCESS: '[AUTH] LOGIN_SUCCESS',
  LOGIN_FAILURE: '[AUTH] LOGIN_FAILURE',
  SIGNUP_REQUEST: '[AUTH] SIGNUP REQUEST',
  SIGNUP_SUCCESS: '[AUTH] SIGNUP_SUCCESS',
  SIGNUP_FAILURE: '[AUTH] SIGNUP_FAILURE',
  REQUEST_LOGOUT: '[AUTH] REQUEST LOGOUT',
  LOGOUT: '[AUTH] LOGOUT',
};
